### ISSUE TITLE
`pyasn1.compat.octets` has been removed in 0.6.1

### ISSUE THREAD

**Issue by mgorny** [pyasn1/pyasn1-modules#19]
The 0.6.1 release of `pyasn1` removed the `pyasn1.compat.octets` module. As a result, the test suite in `pyasn1-modules` now fails:

```pytb
$ tox -e py312
py312: install_deps> python -I -m pip install 'pyasn1<0.7.0,>=0.4.6'
.pkg: install_requires> python -I -m pip install setuptools
.pkg: _optional_hooks> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_sdist> python -I -m pip install setuptools
.pkg: get_requires_for_build_wheel> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_wheel> python -I -m pip install setuptools
.pkg: prepare_metadata_for_build_wheel> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py312: install_package_deps> python -I -m pip install 'pyasn1<0.7.0,>=0.4.6'
py312: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/pyasn1-modules/.tox/.tmp/package/1/pyasn1_modules-0.4.1.tar.gz
py312: commands[0]> .tox/py312/bin/python -m unittest discover -s tests
E........................................................................E...................E....E............................................................E..........................EE......................................................................................
======================================================================
ERROR: test_pem (unittest.loader._FailedTest.test_pem)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_pem
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_pem.py", line 10, in <module>
    from pyasn1.compat.octets import ints2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc3770 (unittest.loader._FailedTest.test_rfc3770)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc3770
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc3770.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc4073 (unittest.loader._FailedTest.test_rfc4073)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc4073
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc4073.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc4334 (unittest.loader._FailedTest.test_rfc4334)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc4334
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc4334.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc5755 (unittest.loader._FailedTest.test_rfc5755)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc5755
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc5755.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc6032 (unittest.loader._FailedTest.test_rfc6032)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc6032
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc6032.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


======================================================================
ERROR: test_rfc6120 (unittest.loader._FailedTest.test_rfc6120)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_rfc6120
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/tmp/pyasn1-modules/tests/test_rfc6120.py", line 13, in <module>
    from pyasn1.compat.octets import str2octs
ModuleNotFoundError: No module named 'pyasn1.compat.octets'


----------------------------------------------------------------------
Ran 274 tests in 1.457s

FAILED (errors=7)
py312: exit 1 (2.98 seconds) /tmp/pyasn1-modules> .tox/py312/bin/python -m unittest discover -s tests pid=94304
  py312: FAIL code 1 (16.98=setup[14.00]+cmd[2.98] seconds)
  evaluation failed :( (17.10 seconds)
```

**Comment by mgorny** [comment]
Ping. The latest releases are broken for almost two months now.

**Comment by a-detiste** [comment]
patched in Debian https://github.com/pyasn1/pyasn1-modules/pull/24
