### ISSUE TITLE
Problem installing new version 0.4.1

### ISSUE THREAD

**Issue by matheuspinheirosantos** [pyasn1/pyasn1-modules#20]
Since today, with the release of the new version, I am having problems in the build of my project.

```
Installing pyasn1-modules (0.4.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/home/circleci/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/home/circleci/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/circleci/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 128, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "/home/circleci/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 61, in _build_backend
      ep = os.environ["_PYPROJECT_HOOKS_BUILD_BACKEND"]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen os>", line 679, in __getitem__
  KeyError: '_PYPROJECT_HOOKS_BUILD_BACKEND'
  

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyasn1-modules (0.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pyasn1-modules (==0.4.1)"'.
``` 

We are using python 3.11.7 and poetry 1.7.1

**Comment by yemiajayi** [comment]
Started experiencing the same issue a few hours ago, too:

```
ChefBuildError
  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 128, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 61, in _build_backend
      ep = os.environ["_PYPROJECT_HOOKS_BUILD_BACKEND"]
    File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
      raise KeyError(key) from None
  KeyError: '_PYPROJECT_HOOKS_BUILD_BACKEND'
  
  at /usr/local/lib/python3.9/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with pyasn1-modules (0.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyasn1-modules (==0.4.1)"'.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

python 3.9 and poetry 1.4.1

**Comment by yemiajayi** [comment]
Issue resolved I believe. tried again this morning and it worked.
